replicaCount: 1

image:
  repository: ghcr.io/kahirokunn/runtime-hooks
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
