apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  annotations:
    runtime.cluster.x-k8s.io/inject-ca-from-secret: {{ .Release.Namespace }}/{{ .Release.Name }}-cert
  name: {{ .Release.Name }}-extensionconfig
spec:
  clientConfig:
    service:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - default
